const SampleTreeData = [
  {
    member_id: "1",
    name: "William Doe",
    attributes: {
      image: "mem1",
      DOB: "1920-01-15",
      gender: "male",
      placeOfBirth: "Springfield",
      bio: "Patriarch of the Doe family.",
      spouseInfo: "Married to Mary Doe",
      dateOfDeath: "",
      contact: "555-1234",
      maritalStatus: "married",
    },
    children: [
      {
        member_id: "1.1",
        name: "George Doe",
        attributes: {
          image: "mem2",
          DOB: "1945-09-18",
          gender: "male",
          placeOfBirth: "Springfield",
          bio: "Eldest son of William.",
          spouseInfo: "Married to Jessica Doe",
          dateOfDeath: "",
          contact: "555-5678",
          maritalStatus: "married",
        },
        children: [
          {
            member_id: "1.1.1",
            name: "Richard Doe",
            attributes: {
              image: "loginImg",
              DOB: "1970-03-12",
              gender: "male",
              placeOfBirth: "Springfield",
              bio: "First child of George.",
              spouseInfo: "Married to Emily Doe",
              dateOfDeath: "",
              contact: "555-8765",
              maritalStatus: "married",
            },
            children: [
              {
                member_id: "1.1.1.1",
                name: "John Doe",
                attributes: {
                  image: "mem4",
                  DOB: "1995-10-01",
                  gender: "male",
                  placeOfBirth: "Springfield",
                  bio: "First child of Richard.",
                  spouseInfo: "",
                  dateOfDeath: "",
                  contact: "555-4321",
                  maritalStatus: "single",
                },
                children: [
                  {
                    member_id: "1.1.1.1.1",
                    name: "Lucas Doe",
                    attributes: {
                      image: "loginImg",
                      DOB: "2020-08-14",
                      gender: "male",
                      placeOfBirth: "Springfield",
                      bio: "Son of John.",
                      spouseInfo: "",
                      dateOfDeath: "",
                      contact: "",
                      maritalStatus: "single",
                    },
                  },
                  {
                    member_id: "1.1.1.1.2",
                    name: "Sophia Doe",
                    attributes: {
                      image: "mem3",
                      DOB: "2023-04-27",
                      gender: "female",
                      placeOfBirth: "Springfield",
                      bio: "Daughter of John.",
                      spouseInfo: "",
                      dateOfDeath: "",
                      contact: "",
                      maritalStatus: "single",
                    },
                  },
                ],
              },
              {
                member_id: "1.1.1.2",
                name: "Sarah Doe",
                attributes: {
                  image: "mem3",
                  DOB: "1998-02-20",
                  gender: "female",
                  placeOfBirth: "Springfield",
                  bio: "Second child of Richard.",
                  spouseInfo: "",
                  dateOfDeath: "",
                  contact: "",
                  maritalStatus: "single",
                },
                children: [
                  {
                    member_id: "1.1.1.2.1",
                    name: "Ella Smith",
                    attributes: {
                      image: "mem3",
                      DOB: "2022-09-30",
                      gender: "female",
                      placeOfBirth: "Springfield",
                      bio: "Daughter of Sarah.",
                      spouseInfo: "",
                      dateOfDeath: "",
                      contact: "",
                      maritalStatus: "single",
                    },
                  },
                ],
              },
            ],
          },
          {
            member_id: "1.1.2",
            name: "Robert Doe",
            attributes: {
              image: "mem3",
              DOB: "1973-08-30",
              gender: "male",
              placeOfBirth: "Springfield",
              bio: "Second son of George.",
              spouseInfo: "",
              dateOfDeath: "",
              contact: "",
              maritalStatus: "single",
            },
            children: [
              {
                member_id: "1.1.2.1",
                name: "James Doe",
                attributes: {
                  image: "mem3",
                  DOB: "2000-04-22",
                  gender: "male",
                  placeOfBirth: "Springfield",
                  bio: "Son of Robert.",
                  spouseInfo: "",
                  dateOfDeath: "",
                  contact: "",
                  maritalStatus: "single",
                },
              },
              {
                member_id: "1.1.2.2",
                name: "Olivia Doe",
                attributes: {
                  image: "mem3",
                  DOB: "2003-07-09",
                  gender: "female",
                  placeOfBirth: "Springfield",
                  bio: "Daughter of Robert.",
                  spouseInfo: "",
                  dateOfDeath: "",
                  contact: "",
                  maritalStatus: "single",
                },
              },
            ],
          },
          {
            member_id: "1.1.3",
            name: "Patricia Doe",
            attributes: {
              image: "mem3",
              DOB: "1976-12-21",
              gender: "female",
              placeOfBirth: "Springfield",
              bio: "Only daughter of George.",
              spouseInfo: "",
              dateOfDeath: "",
              contact: "",
              maritalStatus: "single",
            },
            children: [
              {
                member_id: "1.1.3.1",
                name: "Emma Johnson",
                attributes: {
                  image: "mem3",
                  DOB: "2005-05-17",
                  gender: "female",
                  placeOfBirth: "Springfield",
                  bio: "Daughter of Patricia.",
                  spouseInfo: "",
                  dateOfDeath: "",
                  contact: "",
                  maritalStatus: "single",
                },
              },
              {
                member_id: "1.1.3.2",
                name: "Noah Johnson",
                attributes: {
                  image: "mem3",
                  DOB: "2008-11-11",
                  gender: "male",
                  placeOfBirth: "Springfield",
                  bio: "Son of Patricia.",
                  spouseInfo: "",
                  dateOfDeath: "",
                  contact: "",
                  maritalStatus: "single",
                },
              },
            ],
          },
        ],
      },
      {
        member_id: "1.2",
        name: "Charles Doe",
        attributes: {
          image: "mem3",
          DOB: "1948-12-27",
          gender: "male",
          placeOfBirth: "Springfield",
          bio: "Youngest son of William.",
          spouseInfo: "Married to Linda Doe",
          dateOfDeath: "",
          contact: "555-8765",
          maritalStatus: "married",
        },
        children: [
          {
            member_id: "1.2.1",
            name: "Henry Doe",
            attributes: {
              image: "mem3",
              DOB: "1975-09-05",
              gender: "male",
              placeOfBirth: "Springfield",
              bio: "Eldest son of Charles.",
              spouseInfo: "",
              dateOfDeath: "",
              contact: "",
              maritalStatus: "single",
            },
            children: [
              {
                member_id: "1.2.1.1",
                name: "Lily Doe",
                attributes: {
                  image: "mem3",
                  DOB: "2001-02-14",
                  gender: "female",
                  placeOfBirth: "Springfield",
                  bio: "Daughter of Henry.",
                  spouseInfo: "",
                  dateOfDeath: "",
                  contact: "",
                  maritalStatus: "single",
                },
              },
              {
                member_id: "1.2.1.2",
                name: "Ethan Doe",
                attributes: {
                  image: "mem3",
                  DOB: "2004-10-23",
                  gender: "male",
                  placeOfBirth: "Springfield",
                  bio: "Son of Henry.",
                  spouseInfo: "",
                  dateOfDeath: "",
                  contact: "",
                  maritalStatus: "single",
                },
              },
            ],
          },
          {
            member_id: "1.2.2",
            name: "Margaret Doe",
            attributes: {
              image: "mem2",
              DOB: "1978-06-16",
              gender: "female",
              placeOfBirth: "Springfield",
              bio: "Only daughter of Charles.",
              spouseInfo: "",
              dateOfDeath: "",
              contact: "",
              maritalStatus: "single",
            },
            children: [
              {
                member_id: "1.2.2.1",
                name: "Zoe Brown",
                attributes: {
                  image: "mem3",
                  DOB: "2006-07-07",
                  gender: "female",
                  placeOfBirth: "Springfield",
                  bio: "Daughter of Margaret.",
                  spouseInfo: "",
                  dateOfDeath: "",
                  contact: "",
                  maritalStatus: "single",
                },
              },
              {
                member_id: "1.2.3",
                name: "Thomas Doe",
                attributes: {
                  image: "mem3",
                  DOB: "1980-11-01",
                  gender: "male",
                  placeOfBirth: "Springfield",
                  bio: "Second son of Charles.",
                  spouseInfo: "",
                  dateOfDeath: "",
                  contact: "",
                  maritalStatus: "single",
                },
                children: [
                  {
                    member_id: "1.2.3.1",
                    name: "Daniel Doe",
                    attributes: {
                      image: "mem2",
                      DOB: "2010-01-05",
                      gender: "male",
                      placeOfBirth: "Springfield",
                      bio: "Son of Thomas.",
                      spouseInfo: "",
                      dateOfDeath: "2018-01-05",
                      contact: "",
                      maritalStatus: "single",
                    },
                  },
                  {
                    member_id: "1.2.3.2",
                    name: "Grace Doe",
                    attributes: {
                      image: "mem4",
                      DOB: "2013-06-22",
                      gender: "female",
                      placeOfBirth: "Springfield",
                      bio: "Daughter of Thomas.",
                      spouseInfo: "",
                      dateOfDeath: "",
                      contact: "",
                      maritalStatus: "single",
                    },
                    children: [
                      {
                        member_id: "1.2.3",
                        name: "Thomas Doe",
                        attributes: {
                          image: "mem3",
                          DOB: "1980-11-01",
                          gender: "male",
                          placeOfBirth: "Springfield",
                          bio: "Second son of Charles.",
                          spouseInfo: "",
                          dateOfDeath: "",
                          contact: "",
                          maritalStatus: "single",
                        },
                        children: [
                          {
                            member_id: "1.2.3.1",
                            name: "Daniel Doe",
                            attributes: {
                              image: "mem2",
                              DOB: "2010-01-05",
                              gender: "male",
                              placeOfBirth: "Springfield",
                              bio: "Son of Thomas.",
                              spouseInfo: "",
                              dateOfDeath: "2018-01-05",
                              contact: "",
                              maritalStatus: "single",
                            },
                          },
                          {
                            member_id: "1.2.3.2",
                            name: "Grace Doe",
                            attributes: {
                              image: "mem4",
                              DOB: "2013-06-22",
                              gender: "female",
                              placeOfBirth: "Springfield",
                              bio: "Daughter of Thomas.",
                              spouseInfo: "",
                              dateOfDeath: "",
                              contact: "",
                              maritalStatus: "single",
                            },
                          },
                        ],
                      },
                      {
                        member_id: "1.2.3",
                        name: "Thomas Doe",
                        attributes: {
                          image: "mem3",
                          DOB: "1980-11-01",
                          gender: "male",
                          placeOfBirth: "Springfield",
                          bio: "Second son of Charles.",
                          spouseInfo: "",
                          dateOfDeath: "",
                          contact: "",
                          maritalStatus: "single",
                        },
                        children: [
                          {
                            member_id: "1.2.3.1",
                            name: "Daniel Doe",
                            attributes: {
                              image: "mem2",
                              DOB: "2010-01-05",
                              gender: "male",
                              placeOfBirth: "Springfield",
                              bio: "Son of Thomas.",
                              spouseInfo: "",
                              dateOfDeath: "2018-01-05",
                              contact: "",
                              maritalStatus: "single",
                            },
                          },
                          {
                            member_id: "1.2.3.2",
                            name: "Grace Doe",
                            attributes: {
                              image: "mem4",
                              DOB: "2013-06-22",
                              gender: "female",
                              placeOfBirth: "Springfield",
                              bio: "Daughter of Thomas.",
                              spouseInfo: "",
                              dateOfDeath: "",
                              contact: "",
                              maritalStatus: "single",
                            },
                          },
                        ],
                      },
                      {
                        member_id: "1.2.3",
                        name: "Thomas Doe",
                        attributes: {
                          image: "mem3",
                          DOB: "1980-11-01",
                          gender: "male",
                          placeOfBirth: "Springfield",
                          bio: "Second son of Charles.",
                          spouseInfo: "",
                          dateOfDeath: "",
                          contact: "",
                          maritalStatus: "single",
                        },
                        children: [
                          {
                            member_id: "1.2.3.1",
                            name: "Daniel Doe",
                            attributes: {
                              image: "mem2",
                              DOB: "2010-01-05",
                              gender: "male",
                              placeOfBirth: "Springfield",
                              bio: "Son of Thomas.",
                              spouseInfo: "",
                              dateOfDeath: "2018-01-05",
                              contact: "",
                              maritalStatus: "single",
                            },
                          },
                          {
                            member_id: "1.2.3.2",
                            name: "Grace Doe",
                            attributes: {
                              image: "mem4",
                              DOB: "2013-06-22",
                              gender: "female",
                              placeOfBirth: "Springfield",
                              bio: "Daughter of Thomas.",
                              spouseInfo: "",
                              dateOfDeath: "",
                              contact: "",
                              maritalStatus: "single",
                            },
                            children: [
                              {
                                member_id: "1.2.3",
                                name: "Thomas Doe",
                                attributes: {
                                  image: "mem3",
                                  DOB: "1980-11-01",
                                  gender: "male",
                                  placeOfBirth: "Springfield",
                                  bio: "Second son of Charles.",
                                  spouseInfo: "",
                                  dateOfDeath: "",
                                  contact: "",
                                  maritalStatus: "single",
                                },
                                children: [
                                  {
                                    member_id: "1.2.3.1",
                                    name: "Daniel Doe",
                                    attributes: {
                                      image: "mem2",
                                      DOB: "2010-01-05",
                                      gender: "male",
                                      placeOfBirth: "Springfield",
                                      bio: "Son of Thomas.",
                                      spouseInfo: "",
                                      dateOfDeath: "2018-01-05",
                                      contact: "",
                                      maritalStatus: "single",
                                    },
                                  },
                                  {
                                    member_id: "1.2.3.2",
                                    name: "Grace Doe",
                                    attributes: {
                                      image: "mem4",
                                      DOB: "2013-06-22",
                                      gender: "female",
                                      placeOfBirth: "Springfield",
                                      bio: "Daughter of Thomas.",
                                      spouseInfo: "",
                                      dateOfDeath: "",
                                      contact: "",
                                      maritalStatus: "single",
                                    },
                                  },
                                ],
                              },
                              {
                                member_id: "1.2.3",
                                name: "Thomas Doe",
                                attributes: {
                                  image: "mem3",
                                  DOB: "1980-11-01",
                                  gender: "male",
                                  placeOfBirth: "Springfield",
                                  bio: "Second son of Charles.",
                                  spouseInfo: "",
                                  dateOfDeath: "",
                                  contact: "",
                                  maritalStatus: "single",
                                },
                                children: [
                                  {
                                    member_id: "1.2.3.1",
                                    name: "Daniel Doe",
                                    attributes: {
                                      image: "mem2",
                                      DOB: "2010-01-05",
                                      gender: "male",
                                      placeOfBirth: "Springfield",
                                      bio: "Son of Thomas.",
                                      spouseInfo: "",
                                      dateOfDeath: "2018-01-05",
                                      contact: "",
                                      maritalStatus: "single",
                                    },
                                  },
                                  {
                                    member_id: "1.2.3.2",
                                    name: "Grace Doe",
                                    attributes: {
                                      image: "mem4",
                                      DOB: "2013-06-22",
                                      gender: "female",
                                      placeOfBirth: "Springfield",
                                      bio: "Daughter of Thomas.",
                                      spouseInfo: "",
                                      dateOfDeath: "",
                                      contact: "",
                                      maritalStatus: "single",
                                    },
                                  },
                                ],
                              },
                            ],
                          },
                        ],
                      },
                    ],
                  },
                ],
              },
            ],
          },
          {
            member_id: "1.2.3",
            name: "Thomas Doe",
            attributes: {
              image: "mem3",
              DOB: "1980-11-01",
              gender: "male",
              placeOfBirth: "Springfield",
              bio: "Second son of Charles.",
              spouseInfo: "",
              dateOfDeath: "",
              contact: "",
              maritalStatus: "single",
            },
            children: [
              {
                member_id: "1.2.3.1",
                name: "Daniel Doe",
                attributes: {
                  image: "mem2",
                  DOB: "2010-01-05",
                  gender: "male",
                  placeOfBirth: "Springfield",
                  bio: "Son of Thomas.",
                  spouseInfo: "",
                  dateOfDeath: "2018-01-05",
                  contact: "",
                  maritalStatus: "single",
                },
              },
              {
                member_id: "1.2.3.2",
                name: "Grace Doe",
                attributes: {
                  image: "mem4",
                  DOB: "2013-06-22",
                  gender: "female",
                  placeOfBirth: "Springfield",
                  bio: "Daughter of Thomas.",
                  spouseInfo: "",
                  dateOfDeath: "",
                  contact: "",
                  maritalStatus: "single",
                },
              },
            ],
          },
        ],
      },
    ],
  },
];
